version: '3.8'
services:
  posthog:
    image: posthog/posthog:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://posthog:password@db:5432/posthog
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=some-secret-key
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posthog

  redis:
    image: redis:6
